# Generated by Django 3.2.16 on 2025-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для публикации.', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
